<?php 
	if ($this->pageCount == 1) return '';
	$ssFilter			= $this->ssFilter;
	
	$slbCountPerPage = $this->zvnFormSelect('filter_count_perpage',null , array ('5' => '5','10' => '10','25' => '25','50' => '50'), $ssFilter['filter_count_perpage'],array('class'=>'input-md'));
	//parentId 
	$parentId		= $ssFilter['parent_id'];
	// Link
	$this->currentURL	= $this->currentURL . 'page/';
	$linkStart		= $this->currentURL . $this->first.'/'.$parentId;
	$linkEnd		= $this->currentURL . $this->last.'/'.$parentId;
	$linkNext		= $this->currentURL . $this->next.'/'.$parentId;
	$linkPrevious	= $this->currentURL . $this->previous.'/'.$parentId;
	
	// Button
	$startXhtml		= '<li class="disabled"><a href="#">&laquo;</a></li>';
	$previousXhtml	= '<li class="disabled"><a href="#">Trước</a></li>';
	$nextXhtml		= '<li class="disabled"><a href="#">Tiếp</a></li>';
	$endXhtml		= '<li class="disabled"><a href="#">&raquo;</a></li>';
	
	if($this->current != 1){
		$startXhtml		= sprintf('<li><a href="%s">&laquo;</a></li>', $linkStart);
		$previousXhtml	= sprintf('<li><a href="%s">Trước</a></li>', $linkPrevious);
	}
	
	if($this->current != $this->last){
		$nextXhtml		= sprintf('<li><a href="%s">Tiếp</a></li>', $linkNext);
		$endXhtml		= sprintf('<li><a href="%s">&raquo;</a></li>', $linkEnd);
	}
	
	$pagesInRange	= '';
	foreach ($this->pagesInRange as $key) {
		$linkPage				=	$this->currentURL . $key.'/'.$parentId;
		if($this->current == $key) {
			$pagesInRange	.= sprintf('<li class="active"><a href="#">%s<span class="sr-only">(current)</span></a></li>',$key);
		}else{
			$pagesInRange	.= sprintf('<li><a href="%s">%s</a></li>', $linkPage, $key);
		}
	}
?>
<div class="row">
	<div class="col-xs-6">
		<div id="example1_length" class="dataTables_length">
			<label>
				<?php echo 'Số bản ghi trên trang ' . $slbCountPerPage .' ';?>
				<?php echo sprintf('Hiển thị %s đến %s trong tổng số %s bản ghi.', $this->firstItemNumber, $this->lastItemNumber ,$this->totalItemCount); ?>
			</label>
		</div>
	</div>
	<div class="col-xs-6">
		<div class="dataTables_paginate paging_bootstrap">
			<ul class="pagination pagination-sm no-margin pull-right">
				<?php echo $startXhtml;?>
				<?php echo $previousXhtml;?>
				<?php echo $pagesInRange;?>
				<?php echo $nextXhtml;?>
				<?php echo $endXhtml;?>
			</ul>
		</div>
	</div>
</div>
